procpu/Controllers/TranscriptController.cs
using Microsoft.Reporting.WebForms;
using procpu.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Net;
using procpu;
using WebGrease.Css.Extensions;
using System.Data.SqlClient;
using System.Configuration;
using System.Web.UI.WebControls;
using procpu.rdlc;

namespace procpu.Controllers

{
    [Authorize]
    public class TranscriptController : Controller
    {
        // GET: Transcript
        db_luccpuEntities db = new db_luccpuEntities();
        public ActionResult generatetranscript()
        {
            var stdtls = (from std in db.tblstdapplicationdtls
                          select new DropdownViewModel
                          {
                              transid = std.transid,
                              stdname = std.stdfname + " " + std.stdmname + " " + std.stdlname + " (" + std.citizenship_id + ")"
                          }).ToList();
            if (stdtls != null)
            {
                ViewBag.ListOfStudent = new SelectList(stdtls, "transid", "stdname");
            }          
            List<tblattachmenttype> attac = db.tblattachmenttypes.ToList();
            List<SelectListItem> list = new List<SelectListItem>();         
            for (int i = 0; i < attac.Count; i++)
            {
                list.Add(new SelectListItem { Text = attac[i].attachmentname, Value = attac[i].transid.ToString() });
            }
            ViewBag.item = new MultiSelectList(list.OrderBy(a => a.Text), "Value", "Text");
            return View();
        }

        public ActionResult studentinformation(Guid value)
        {
            string result = "";
            List<string> msg = new List<string>();
            var exists = db.tblstdapplicationdtls.OrderBy(a => a.rcm).Where(x => x.transid == value).FirstOrDefault();
            if (exists != null)
            {
                var detail = (from x in db.tblstdapplicationdtls
                              join y in db.tblcountrymasts on x.country equals y.transid
                              join z in db.tblstdparentdtls on x.transid equals z.frmmodtransid
                              where x.transid == value
                              select new DropdownViewModel
                              {
                                  stdfname = x.stdfname,
                                  stdmname = x.stdmname,
                                  stdlname = x.stdlname,
                                  phno = x.phno,
                                  address = x.address,
                                  country = y.country_name,
                                  fname = z.fname,
                                  lname = z.lname,
                                  email = z.email,
                                  dob = x.dob,
                              }).ToList();
                ViewBag.detailsby_id = detail;
                result = "sucess";
                msg.Add(result.ToString());
                return View();

            }
            else
            {
                result = "error";
                msg.Add(result.ToString());
                msg.Add("Entered Name is invalid.");
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymousAttribute]
        public JsonResult SaveTranscriptRecord(TranscriptViewModel model)
        {
            string result = "";
            List<string> msg = new List<string>();
            Guid id = Guid.NewGuid();
            //var ids = Guid.Parse(model.stdfname);
            //var exists = db.tblstdtranscripts.OrderBy(a => a.rcm).Where(x => x.frmmodtransid == ids).FirstOrDefault();
            if (ModelState.IsValid)
                {
                //if (exists == null)
                //{
                        tblstdtranscript Tra = new tblstdtranscript();
                        Tra.transid = id;
                        Tra.frmmodtransid = Guid.Parse(model.stdfname);
                        Tra.transgendt = model.transgendt;
                        Tra.rco = "Admin";
                        Tra.rcm = DateTime.Now;
                        Tra.delsts = "0";
                        db.tblstdtranscripts.Add(Tra);

                        tblstdacademicrecord Aca = new tblstdacademicrecord();
                        for (int i = 0; i < model.coursetitle.Count; i++)
                        {
                            if (model.coursetitle[i] != null && model.assignments[i] != null && model.quizzes[i] != null && model.marksobtained[i] != null && model.totalmarks[i] != null && model.finalgrade[i] != null)
                            {
                            db.tblstdacademicrecords.Add(new tblstdacademicrecord()
                            {
                                transid = Guid.NewGuid(),
                                frmmodtransid = id,
                                coursetitle = model.coursetitle[i],
                                //creditattempted = Convert.ToDecimal(model.creditattempted[i]),
                                //creditearned = Convert.ToDecimal(model.creditearned[i]),
                                assignments = model.assignments[i],
                                quizzes = model.quizzes[i],
                                marksobtained = model.marksobtained[i],
                                totalmarks = model.totalmarks[i],
                                    finalgrade = model.finalgrade[i],
                                    rco = "Admin",                       
                                    rcm = DateTime.Now,
                                    delsts = "0",
                                    studenttransid = Guid.Parse(model.stdfname)

                                }
                                );

                            }
                        }
                        tblstdacademicgradedtl Gra = new tblstdacademicgradedtl();
                        Gra.transid = Guid.NewGuid();
                        Gra.frmmodtransid = id;
                        Gra.schoolyear = model.schoolyear;
                        Gra.gradelvl = model.gradelvl;
                        Gra.totalcredits = model.totalcredits;
                        Gra.gpa = model.gpa;
                        Gra.cumulativegpa = model.cumulativegpa;
                        Gra.rco = "Admin";
                        Gra.rcm = DateTime.Now;
                        Gra.delsts = "0";
                        Gra.studenttransid = Guid.Parse(model.stdfname);
                        db.tblstdacademicgradedtls.Add(Gra);

                        tblstdacademicsummary Sum = new tblstdacademicsummary();
                        Sum.transid = Guid.NewGuid();
                        Sum.frmmodtransid = id;
                    Sum.cumugpa = model.cumugpa;
                    Sum.creditsattempted = model.creditsattempted;
                    Sum.creditsearned = model.creditsearned;
                    Sum.diplomaearned = model.diplomaearned;
                    Sum.totalsubjects = model.totalsubjects;
                    Sum.totalmarksattempted = model.totalmarksattempted;
                    Sum.totalmarksobtained = model.totalmarksobtained;
                    Sum.totalpercentage = model.totalpercentage;
                        Sum.graduationdate = model.graduationdate;
                        Sum.rco = "Admin";
                        Sum.rcm = DateTime.Now;
                        Sum.delsts = "0";
                        Sum.studenttransid = Guid.Parse(model.stdfname);
                        db.tblstdacademicsummaries.Add(Sum);

                        for (int i = 0; i < model.attachmenttype.Count; i++)
                        {
                            tblstdattachment Attach = new tblstdattachment();
                            Attach.transid = Guid.NewGuid();
                            Attach.frmmodtransid = id;
                            Attach.attachmenttype = model.attachmenttype[i];
                            if (model.attachmenttype[i].ToUpper() == "7177259E-60CF-4006-83D5-1ACA6F0440C5")
                            {
                                Attach.attachmentotherdtls = model.attachmentotherdtls;
                            }
                            else
                            {
                                Attach.attachmentotherdtls = null;
                            }
                            Attach.rco = "Admin";
                            Attach.rcm = DateTime.Now;
                            Attach.delsts = "0";
                            Attach.studenttransid = Guid.Parse(model.stdfname);
                           db.tblstdattachments.Add(Attach);
                        }

                        db.SaveChanges();
                        result = "true";
                        msg.Add(result.ToString());
                        msg.Add("All the records have been added sucessfully.");
                    //}
                //else
                //{
                //    result = "false";
                //    msg.Add(result.ToString());
                //    msg.Add("This Student is already exists.");
                //}
            }

                else
                {
                    result = "false";
                    msg.Add(result.ToString());
                    msg.Add("Please fill up all the fields correctly.");
                }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateTranscriptRecord(EditViewModel model)
        {
            string result = "";
            List<string> msg = new List<string>();
            var transcriptid = model.transid;
            if (ModelState.IsValid)
            {

procpu/Views/Transcript/alltranscript.cshtml
@model procpu.Models.TableViewModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
</head>

<body>
    <div class="col-sm-12">
        <table id="all" class="table table-striped table-bordered" style="width:100%">
            <thead>

                <tr><th class="hidden">Transid</th>
                    <th>Student Name</th>
                    <th>Citizenship ID</th>
                    <th>Transcript Generation Date</th>
                    <th>School Year</th>
                    <th>Download Transcipt</th>
                    <th>Edit Transcipt</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in ViewBag.tblview)
            {
                    <tr>
                        <td class="hidden">@item.transid</td>
                        <td>@(item.stdfname + " " + item.stdmname + " " + item.stdlname)</td>
                        <td>@item.citizenship_id</td>
                        <td>@item.transgendt.ToString("dd-MM-yyyy")</td>
                        <td>@item.schoolyear</td>
                        <td><a class="btn btn-success" href="@Url.Action("download", "Transcript", new {id= @item.transid })"><i class="fa fa-download"></i></a></td>
                        <td><a class="btn btn-warning" onclick="LoadInfo('@item.transid')" href="#"><i class="fa fa-edit"></i></a></td>
                    </tr>
                }


            </tbody>
        </table>

    </div>


</body>
</html>
<script>
    $(document).ready(function () {
        $('#all').DataTable();
    });
    function LoadInfo(transid) {
        debugger;
        var url = '@Url.Action("edittranscript", "Transcript")?id=' + transid;
        window.location.href = (url);
       }
</script>

procpu/Views/Transcript/downloadtranscript.cshtml
@model procpu.Models.TableViewModel
@{
    ViewBag.Title = "downloadtranscript";
    Layout = "~/Views/Shared/_CPULayout.cshtml";
}
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<h2 style="text-align:center; color:black"><b>TRANSCRIPT DOWNLOAD</b></h2>
<div class="container" id="transall" style="margin-bottom:500px;">

</div>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('#transall').load('@Url.Action("alltranscript", "Transcript")');
    })
</script>

procpu/Views/Transcript/editbyid.cshtml
@model procpu.Models.EditViewModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
</head>

<body>


    <div class="col-sm-6">
        @foreach (var item in ViewBag.editby_id)
        {
            <input type="hidden" id="Id" name="Id" value="@item.transid">
            <label><b>Full Name: </b>@(item.stdfname + " " + item.stdmname + " " + item.stdlname)</label><br />
            <label><b>Address: </b>@(item.address + ", " + item.country_name) </label><br />
            <label><b>Phone Number: </b>@item.phno</label><br />
                <label><b>E-mail Address: </b>@item.email</label><br />
                <label><b>Date of Birth: </b>@item.dob.ToString("dd-MM-yyyy")</label><br />
                <label><b>Parent/Guardian: </b>@(item.fname + " " + item.lname)</label><br />
        }
    </div>
</body>
</html>

procpu/Views/Transcript/studentinformation.cshtml
@model procpu.Models.DropdownViewModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
</head>

<body>


    <div class="col-sm-6">
        @foreach (var item in ViewBag.detailsby_id)
            {
            <input type="hidden" id="Id" name="Id" value="@item.transid">
            <label><b>Full Name: </b>@(item.stdfname + " " + item.stdmname + " " + item.stdlname)</label><br />
            <label><b>Address: </b>@(item.address + ", " + item.country) </label><br />                     
                <label><b>Phone Number: </b>@item.phno</label><br />
                <label><b>E-mail Address: </b>@item.email</label><br />
                <label><b>Date of Birth: </b>@item.dob.ToString("dd-MM-yyyy")</label><br />
                <label><b>Parent/Guardian: </b>@(item.fname +  " " + item.lname)</label><br />
        }
    </div>
</body>
</html>