procpu/Controllers/AdmissionController.cs
using procpu.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Net;
using procpu;

namespace procpu.Controllers
{
    public class AdmissionController : Controller
    {
        db_luccpuEntities db = new db_luccpuEntities();
        public ActionResult stdadmissiondtls()

        {
            List<tblcountrymast> CountryList = db.tblcountrymasts.ToList();
            ViewBag.ListOfCountry = new SelectList(CountryList, "transid", "country_name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymousAttribute]
        public JsonResult SaveDataInDatabase(AdmissionViewModel model)
        {
            string result = "";
            List<string> msg = new List<string>();
            Guid id = Guid.NewGuid();

            var query = db.tblstdapplicationdtls.Where(x => x.citizenship_id == model.citizenship_id).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (query == null)
                {
                    string fileup = "../uploadfile/" + Guid.NewGuid() + System.IO.Path.GetExtension(model.fileupload.FileName);
                    tblstdapplicationdtl Stu = new tblstdapplicationdtl();
                    Stu.transid = id;
                    Stu.stdfname = model.stdfname;
                    Stu.stdmname = model.stdmname;
                    Stu.stdlname = model.stdlname;
                    Stu.dob = model.dob;
                    Stu.citizenship_id = model.citizenship_id;
                    Stu.gender = model.gender;
                    Stu.address = model.address;
                    Stu.country = Guid.Parse(model.country);
                    Stu.phno = model.phno;
                    Stu.grade = model.grade;
                    Stu.subjectstaken = model.subjectstaken;
                    Stu.pathway = model.pathway;
                    Stu.centrename = model.centrename;
                    Stu.centreaddress = model.centreaddress;
                    Stu.centrephno = model.centrephno;
                    Stu.rco = "Admin";
                    Stu.rcm = DateTime.Now;
                    Stu.delsts = "0";
                    db.tblstdapplicationdtls.Add(Stu);


                    tblstdparentdtl Pre = new tblstdparentdtl();
                    Pre.transid = Guid.NewGuid();
                    Pre.frmmodtransid = id;
                    Pre.fname = model.fname;
                    Pre.lname = model.lname;
                    Pre.idnumber = model.idnumber;
                    Pre.email = model.email;
                    Pre.relation = model.relation;
                    Pre.homeaddress = model.homeaddress;
                    Pre.mobile = model.mobile;
                    Pre.cname = model.cname;
                    Pre.caddress = model.caddress;
                    Pre.suite = model.suite;
                    Pre.state = model.state;
                    Pre.postalcode = model.postalcode;
                    Pre.city = model.city;
                    Pre.cuntry = model.cuntry;
                    Pre.cphno = model.cphno;
                    Pre.howdidyouhearaboutus = model.howdidyouhearaboutus;
                    Pre.fileupload = fileup;
                    Pre.rco = "Admin";
                    Pre.rcm = DateTime.Now;
                    Pre.delsts = "0";
                    db.tblstdparentdtls.Add(Pre);
                    db.SaveChanges();
                    model.fileupload.SaveAs(Server.MapPath(fileup));
                    result = "true";
                    msg.Add(result.ToString());
                    msg.Add("All details has been added sucessfully.");
                }
                else
                {
                    result = "false";
                    msg.Add(result.ToString());
                    msg.Add("This Citizenship ID already exists.");
                }
            }
            else
            {
                result = "false";
                msg.Add(result.ToString());
                msg.Add("Please fill up all the fields correctly.");
            }
            return Json(msg, JsonRequestBehavior.AllowGet);

        }

        public ActionResult StudentDucomentsUpload()
        {
            return View();
        }


        public ActionResult UploadDucoments(string citizenship_id)
        {

            var stddetails = db.tblstdapplicationdtls.OrderBy(a => a.rcm).Where(x => x.citizenship_id == citizenship_id && x.delsts == "0").FirstOrDefault();

            if (stddetails != null)
            {
                var query = db.tblstdapplicationdtls.OrderBy(a => a.rcm).Where(x => x.citizenship_id == citizenship_id && x.delsts == "0");
                ViewBag.studentdetails = query;
                var list = (from x in db.tblstddocuploads
                            join y in db.tbldoctypemasts on x.docid equals y.transid.ToString()
                            join z in db.tblstdapplicationdtls on x.frmmodtransid equals z.transid
                            where z.citizenship_id == citizenship_id
                            select new tblstddocuploadviewmodel
                            {
                                transid = x.transid,

                                frmmodtransid = z.stdfname + " " + z.stdmname + " " + z.stdlname,
                                docid = y.doctype,
                                uploaddocs = x.uploaddocs,
                                rco = x.rco

                            }).ToList();

                ViewBag.docuploaddtls = list;
                List<tbldoctypemast> Ducoments = db.tbldoctypemasts.OrderBy(a => a.rcm).ToList();
                ViewBag.Ducoments = new SelectList(Ducoments, "transid", "doctype");
                return View();
            }
            else
            {
                string result = "Error";
                List<string> msg = new List<string>();
                msg.Add(result);
                msg.Add("Entered ID is invalid.");
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult UploadDucomentsbyid(DucomentsUploadModel uploadmodel)
        {
            bool result = false;
            List<string> msg = new List<string>();
            var filepath = "../uploadfile/" + Guid.NewGuid().ToString() + Path.GetExtension(uploadmodel.upload.FileName);
            if (ModelState.IsValid)
            {
                var details = db.tblstddocuploads.OrderBy(a => a.rcm).Where(x => x.frmmodtransid == new Guid(uploadmodel.frmmodtransid) && x.docid == uploadmodel.doctype).FirstOrDefault();
                if (details == null)
                {
                    tblstddocupload docupload = new tblstddocupload();
                    docupload.transid = Guid.NewGuid();
                    docupload.frmmodtransid = new Guid(uploadmodel.frmmodtransid);
                    docupload.docid = uploadmodel.doctype;
                    docupload.uploaddocs = filepath;
                    docupload.rco = "Applicant";
                    docupload.rcm = DateTime.Now;
                    docupload.delsts = "0";
                    db.tblstddocuploads.Add(docupload);
                    db.SaveChanges();
                    result = true;
                    msg.Add(result.ToString());
                    msg.Add("File Uploaded Successfully...!");
                    uploadmodel.upload.SaveAs(Server.MapPath(filepath));
                }
                else
                {
                    result = true;
                    msg.Add(result.ToString());
                    msg.Add("This Document already exist..");
                }


                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult DeleteDocument(string id)
        {
            var result = false;
            List<string> msg = new List<string>();
            if (id != "")
            {
                Guid docid = new Guid(id);
                tblstddocupload doc = db.tblstddocuploads.OrderBy(a => a.rcm).Where(x => x.transid == new Guid(id)).SingleOrDefault();
                if (System.IO.File.Exists(doc.uploaddocs))
                {
                    System.IO.File.Delete(doc.uploaddocs);
                }
                db.tblstddocuploads.Remove(doc);
                db.SaveChanges();
                result = true;
                msg.Add(result.ToString());
                msg.Add("Document deleted successfully!!");
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public ActionResult applicationdtls()
        {
            return View();
        }

        public ActionResult applicationdtlsbyid(string value)
        {
            string result = "";
            List<string> msg = new List<string>();
            var exist = db.tblstdapplicationdtls.OrderBy(a => a.rcm).Where(x => x.citizenship_id == value).FirstOrDefault();
            if (exist != null)
            {
                var details = (from x in db.tblstdapplicationdtls
                               join y in db.tblcountrymasts on x.country equals y.transid
                               where x.citizenship_id == value
                               select new StudentViewModel
                               {
                                   stdfname = x.stdfname,
                                   stdmname = x.stdmname,
                                   stdlname = x.stdlname,
                                   dob = x.dob,
                                   citizenship_id = x.citizenship_id,
                                   gender = x.gender,

procpu/Views/Admission/StudentDucomentsUpload.cshtml
@model procpu.Models.DucomentsUploadModel
@{
    ViewBag.Title = "StudentDetails";
    Layout = "~/Views/Shared/_CPULayout.cshtml";
}
<style>
    footer {
        background: #e12d3e url(../images/mosaic-pattern.png) repeat;
        background-color: #e12d3e !important;
        width: 100%;
        padding: 15px 0;
        text-align: center;
        bottom: 0px;
        color: #fff;
        margin-top: 20% !important;
    }

    .button-cu {
        border-style: none;
        border-color: inherit;
        border-width: 0;
        background-color: #000;
        background: #000 url(../images/send.png) no-repeat scroll 0% 0%;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        position: relative;
        behavior: url(PIE.htc);
        padding: 5px 30px 5px;
        margin: 0;
        font-family: 'Conv_Helvetica-Condensed',Sans-Serif;
        font-size: 18px;
        color: #fff;
        font-weight: normal;
        line-height: 25px;
        cursor: pointer;
        top: 0px;
        left: 0px;
    }
</style>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<h2 style="text-align:center"><b>Document Upload</b></h2>
<div class="container">
    <div class="col-lg-12">
        <div class="col-sm-offset-3 col-sm-6">
                    <p>Citizenship ID:</p>
            <input type="hidden" id="lblmsg" />
                    <input type="text" class="form-control" id="txtsearch" style="margin-top:21px;" /><br />
                </div>
                <br />
                <br />
                    <button type="button" id="btnsearch" class="button-cu pull-right" style="margin-bottom:50px; margin-right:100px;">Search</button>
                </div>
            </div>
            <br />



            <div class="form-group">

                <div id="details">


                </div>

            </div>
            <script src="~/Scripts/jquery-1.10.2.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>



            <script>
                $(document).ready(function () {
                    $("#btnsearch").click(function () {
                        if (txtsearch.value == "") {
                            alert("Please enter a ID.")
                        }
                        else{
                            var url = $("#txtsearch").val();
                            $.ajax({
                                type: "POST",
                                url: "/Admission/UploadDucoments",
                                data: {
                                    'citizenship_id': url
                                },
                                success: function (msg) {
                                    debugger;
                                    if (msg[0] == 'Error') {
                                        alert(msg[1]);
                                        $("#lblmsg").val("Error");
                                    }
                                    else {
                                        var url = '@Url.Action("UploadDucoments", "Admission")?citizenship_id=' + $("#txtsearch").val();
                                        $("#details").load(url);
                                    }
                                }
                                })
    
                                }
                    })
                       
                        })

          

                    function deletedoc(id) {
                        debugger;
                        $.ajax({
                            type: "POST",
                            url: "/Admission/DeleteDocument?id=" + id,
                            success: function (msg) {
                                if (msg[0]) {
                                    alert(msg[1]);
                                    $("#btnsearch").click();

                                }

                            }
                        })
                    
                }
                function uploadfile(form) {
                    debugger;

                    var ddl = $("#ddldoctype").val();
                    var file1 = document.getElementById('upload');

                    if (ddl != "" && file1.files.length > 0) {
                        var formdata = new FormData(form)
                        $.ajax({
                            type: "POST",
                            url: "/Admission/UploadDucomentsbyid",
                            data: formdata,
                            contentType: false,
                            processData: false,
                            success: function (msg) {
                                debugger;
                                if (msg[0]) {
                                    alert(msg[1]);
                                    $("#myModal").modal("hide");
                                    $('#submitform')[0].reset();
                                    $("#btnsearch").click();
                                    $(".modal-backdrop").hide();
                                    $("body").addClass("modal-close");
                                    $("body").removeClass("modal-open");
                                }

                            }
                        })
                    }
                    else {
                        alert("Please select document and upload file. ")
                    }
                }
            </script>

procpu/Views/Admission/allids.cshtml
@model procpu.Models.StudentViewModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
</head>

<body>
    <div class="col-sm-12">
        <table id="all" class="table table-striped table-bordered" style="width:100%">
            <thead>

                <tr>
                    <th>Name</th>
                    <th>Citizenship ID</th>
                    <th>Phone Number</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in ViewBag.data)
            {
                    <tr>
                        <td>@(item.stdfname + " " + item.stdmname + " " + item.stdlname)</td>
                        <td>@item.citizenship_id</td>
                        <td>@item.phno</td>

                    </tr>
                }


            </tbody>
        </table>

    </div>


</body>
</html>
<script>
    $(document).ready(function () {
        $('#all').DataTable();
    });
</script>

procpu/Views/Admission/applicationdtls.cshtml
@model IEnumerable<procpu.Models.AdmissionViewModel>

@{
    ViewBag.Title = "applicationdtls";
    Layout = "~/Views/Shared/_CPULayout.cshtml";
}
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<style>
    .button-cu {
        border-style: none;
        border-color: inherit;
        border-width: 0;
        background-color: #000;
        background: #000 url(../images/send.png) no-repeat scroll 0% 0%;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        position: relative;
        behavior: url(PIE.htc);
        padding: 5px 30px 5px;
        margin: 0;
        font-family: 'Conv_Helvetica-Condensed',Sans-Serif;
        font-size: 18px;
        color: #fff;
        font-weight: normal;
        line-height: 25px;
        cursor: pointer;
        top: 0px;
        left: 0px;
    }

    body {
        background-color: white;
    }
</style>
<h2 class="text-center"><b>Application Details</b></h2>
<div class="container">
    <div class="col-lg-12">
        <div class="col-sm-offset-3 col-sm-6">
            <p>Citizenship ID:</p>
            <input type="hidden" id="lblmsg" />
            <input type="text" id="Entervalue" style="margin-top:21px;" class="form-control" /><br />
        </div>
        <br />
        <br />
        <input type="submit" id="search" onclick="searchbyid();" class="button-cu pull-right" style="margin-bottom:50px; margin-right:100px;" value="Search" />
    </div>
</div>
<div class="container" id="allid" style="margin-bottom:500px;">


</div>
<div id="divid" class="container" style="margin-bottom:500px;">
    <ul>
        <li><a href="#tabs-1">Student Details</a></li>
        <li><a href="#tabs-2">Parent Details</a></li>
        <li><a href="#tabs-3">Document Details </a></li>
    </ul>

    <div id="tabs-1" style="text-align:left">

    </div>
    <div id="tabs-2">

    </div>
    <div id="tabs-3">

    </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
<script>
        function searchbyid() {
            debugger;
            if (Entervalue.value == "") {
                alert("Please enter a ID.")
            }
            else {
                var viewbyid = $("#Entervalue").val();
                $.ajax({
                    type: "POST",
                    url: "/Admission/applicationdtlsbyid",
                    data: {
                        'value': viewbyid
                    },
                    success: function (msg) {
                        debugger;
                        if (msg[0] == 'error') {
                            alert(msg[1]);
                            $("#lblmsg").val("Error");
                        }
                        else {
                            $('#divid').show();
                            var viewbyid = "@Url.Action("applicationdtlsbyid", "Admission")?value=" + $("#Entervalue").val();
                            $('#tabs-1').load(viewbyid);
                            var pviewbyid = "@Url.Action("parentdtls", "Admission")?value=" + $("#Entervalue").val();
                            $('#tabs-2').load(pviewbyid);
                            var docbyid = "@Url.Action("documentslsbyid", "Admission")?value=" + $("#Entervalue").val();
                            $('#tabs-3').load(docbyid);
                            $('#allid').hide();
                        }

                    }

                })

            }
        }
        $(document).ready(function () {
            $('#allid').load('@Url.Action("allids", "Admission")');
            $('#divid').hide();
        })
        $(function () {
            $("#divid").tabs();
        });
</script>

procpu/Views/Admission/applicationdtlsbyid.cshtml
@model procpu.Models.StudentViewModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
</head>

<body>


    <div class="col-sm-6">
        @foreach (var item in ViewBag.deateilsby_id)
            {
            <input type="hidden" id="custId" name="custId" value="@item.transid">
            <label><b>Name: </b>@(item.stdfname + " " + item.stdmname + " " + item.stdlname)</label><br />
                <label><b>Date of Birth: </b>@item.dob.ToString("dd-MM-yyyy")</label><br />
                <label><b>Citizenship ID: </b>@item.citizenship_id</label><br />
                <label><b>Gender: </b>@item.gender</label><br />
                <label><b>Home Address: </b>@item.address</label><br />
                <label><b>Country: </b>@item.country</label><br />
                <label><b>Phone Number: </b>@item.phno</label><br />
                <label><b>Grade level applied for: </b>@item.grade</label><br />
                <label><b>Subjects Taken: </b>@item.subjectstaken</label><br />
                <label><b>Science / Business/ Medical/Engineering or Accounting or computer science pathway: </b>@item.pathway</label><br />
                <label><b>Centre Name: </b>@item.centrename</label><br />
                <label><b>Centre Address: </b>@item.centreaddress</label><br />
                <label><b>Centre Phone Number: </b>@item.centrephno</label><br />
        }
    </div>
</body>
</html>

procpu/Views/Admission/cpugeneralinformation.cshtml
@model procpu.Models.GeneralViewModel
@{
    Layout = "~/Views/Shared/_CPULayout.cshtml";
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        .chosen-container-single .chosen-single {
            color: #000 !important;
        }

        .button-cu {
            border-style: none;
            border-color: inherit;
            border-width: 0;
            background-color: #000;
            background: #A00 url(../images/send.png) no-repeat scroll 0% 0%;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            position: relative;
            behavior: url(PIE.htc);
            padding: 5px 30px 5px;
            margin: 0;
            font-family: 'Conv_Helvetica-Condensed',Sans-Serif;
            font-size: 18px;
            color: #fff;
            font-weight: normal;
            line-height: 25px;
            cursor: pointer;
            top: 0px;
            left: 0px;
        }

        .tab-content {
            height: 100% !important;
        }

        body {
            background-color: white;
        }
    </style>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="Submit" style="text-align:left">
        @Html.AntiForgeryToken()
        <div class="container" style="color:black">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-horizontal">

                        <h2 style="margin:auto; text-align: center; margin-bottom: 30px; margin-top: 30px;"><b>CPU GENERAL INFORMATION</b></h2>
                        @*@Html.HiddenFor(m => m.transid, new { @id = "ID" })*@
                        <input type="hidden" id="ID" name="transid" />
                        <div class="form-group">
                            @Html.LabelFor(model => model.cpugeninfo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-sm-4">
                                @Html.EditorFor(model => model.cpugeninfo, new { htmlAttributes = new { @class = "form-control", @id = "txtcpugeninfo" } })
                                @Html.ValidationMessageFor(model => model.cpugeninfo, "", new { @class = "text-danger" })
                            </div>
                            @Html.LabelFor(model => model.cpugeninfodesc, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-sm-4">
                                @Html.TextAreaFor(model => model.cpugeninfodesc, new { htmlAttributes = new { @class = "form-control", @id = "txtcpugeninfodesc" } })
                                @Html.ValidationMessageFor(model => model.cpugeninfodesc, "", new { @class = "text-danger" })
                            </div>
                            <br />
                            <br />
                            <div class="form-group">
                                @Html.LabelFor(model => model.geninfoupld, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-sm-4">
                                    <input type="file" name="geninfoupld" id="geninfoupld" class="form-control" required title="Please upload a file."/>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="form-group">
                            <div class="col-md-12 mb-5">

                                <input type="button" class="button-cu pull-right" value="Submit" id="SaveGeneralRecord" onclick="gensave(this.form);" style="background-color:black" />

                            </div>
                            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog">
            <div class="modal-content" style="width: 100%;">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 style="color:#808080">Delete Record</h4>
                </div>
                <div class="modal-body">
                    <h4 style="color:#808080">Are you sure want to delete this record?</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>

                </div>
            </div>
        </div>
    </div>
    <div class="container" id="view" style="margin-bottom:150px;">

    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        function gensave(form) {
            debugger;       
            $.validator.unobtrusive.parse($("#Submit"));
            $("#Submit").validate();
            if ($("#Submit").valid()) {
                var data = new FormData(form);

                $.ajax({
                    type: 'POST',
                    url: "/Admission/SaveData",
                    data: data,
                    contentType: false,
                    processData: false,
                    success: function (msg) {
                        debugger;
                        if (msg[0] == "true") {
                            alert(msg[1]);
                            window.location.href = "/Admission/cpugeneralinformation";

                        }
                        else {
                            alert(msg[1]);
                        }
                    }
                })

            }

        }
        $(document).ready(function () {
            $('#view').load('@Url.Action("generalinformationview", "Admission")');
        })

        function DeleteRecord(transid) {
            $("#ID").val(transid);
            $("#DeleteConfirmation").modal("show")
        }
        function ConfirmDelete() {
            var ID = $("#ID").val();
            $.ajax({
                typr: "POST",
                url: "/Admission/DeleteRecord?transid=" + ID,
                success: function (msg) {
                    if (msg[0] == "success")
                        {
                    $("#DeleteConfirmation").modal("hide");
                    $('#view').load('@Url.Action("generalinformationview", "Admission")');
                        alert(msg[1]);
                    }
                    else {
                        alert(msg[1]);
                    }
                }
            })
        }
    </script>
</body>
</html>

procpu/Views/Admission/documentslsbyid.cshtml
@model procpu.Models.DucomentsUploadModel
@{
    Layout = null;
}
<style>
    div.dataTables_wrapper div.dataTables_filter input {
        margin-left: .5em;
        display: inline-block;
        width: auto;
        width: 77% !important;
    }
</style>
<div class="col-lg-12">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>

            <tr>
                <th>Name</th>
                <th>Document Type</th>
                <th>Upload By</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.docdtls)
            {
                <tr>
                    <td>@(item.frmmodtransid)</td>
                    <td>@item.docid</td>
                    <td>@item.rco</td>
                    <td><a style="color:blue" href="@item.uploaddocs" target="_blank">View</a></td>
                   
                </tr>
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>